### ISSUE TITLE
Issue in Unity WEbGL

### ISSUE THREAD

**Issue by AnkitCIS** [hecomi/UnityScreenSpaceBoolean#2]
Hi,
   i getting issue in project when Switch to unity webGL ,sphere are not visible , when  switch pc platform to webGL Platform.
![webgl_ss](https://user-images.githubusercontent.com/37325415/37328739-4a12532e-26c1-11e8-89d3-75155ef05f27.PNG)
![pcwindows_ss](https://user-images.githubusercontent.com/37325415/37328741-4a4a6e58-26c1-11e8-888c-da5c54263373.PNG)

**Comment by hecomi** [comment]
WebGL 1.0 doesn't have MRT (multiple render target) so we cannot use deferred path correctly (as a result, the command buffer in this demo does not work well with this platform). So please use WebGL 2.0 from **Edit > Graphics Emulation > WebGL 2.0**.
