### ISSUE TITLE
issue with parallel Subtractee 

### ISSUE THREAD

**Issue by AnkitCIS** [hecomi/UnityScreenSpaceBoolean#3]
While putting Subtractee object in parallel direction it not looks real,  next Subtractee objects is looking Blue. 
![screen shot 2018-06-04 at 7 22 52 pm](https://user-images.githubusercontent.com/37325415/40923414-73bcb9e6-6832-11e8-8b35-8cac675f55e5.png)
![screen shot 2018-06-04 at 7 23 02 pm](https://user-images.githubusercontent.com/37325415/40923418-740878cc-6832-11e8-8d55-3a2e847f8fdf.png)
![screen shot 2018-06-04 at 7 23 12 pm](https://user-images.githubusercontent.com/37325415/40923420-743d35a8-6832-11e8-84ed-366b292af9fc.png)
![screen shot 2018-06-04 at 7 23 41 pm](https://user-images.githubusercontent.com/37325415/40923421-746e625e-6832-11e8-8bda-9b0b48ce6625.png)
![screen shot 2018-06-04 at 7 23 56 pm](https://user-images.githubusercontent.com/37325415/40923422-74a12716-6832-11e8-829d-2989bca50021.png)

**Comment by hecomi** [comment]
Sorry for my late reply...

I've written an entry about this screen space boolean example and told it in it (in Japanese):
http://tips.hecomi.com/entry/2016/09/10/191006
This is actually not a bug but a limitation of this method when comparing the depth of subtractors and the cull-front depth buffer.
<img width="1107" alt="default" src="https://user-images.githubusercontent.com/493433/48657504-e5f5d780-ea74-11e8-8280-b927d6f2b9a9.PNG">
